credentials:
  usernames:
    jsmith:
      email: jsmith@gmail.com
      name: John Smith
      password: $2b$12$jqNzvmkbq3mZcbfqb8BVIeNjWc17NdRVh03kr8ztqpQULbqABMGsS # abc
    rbriggs:
      email: rbriggs@gmail.com
      name: Rebecca Briggs
      password: $2b$12$zRL/.DviqLchC7TbF1MmDOnVChzq2tmNRTCcZKdB32UX/QJ6P.T12 # def
cookie:
  expiry_days: 30
  key: random_signature_key 
  name: random_cookie_name
preauthorized:
  emails:
  - melsby@gmail.com