from selenium import webdriver
options = webdriver.ChromeOptions()
options.binary_location = "/usr/bin/chromium-browser"
options.add_argument("--headless")
options.add_argument("window-size=1400,1500")
options.add_argument("--disable-gpu")
options.add_argument("--no-sandbox")
options.add_argument("start-maximized")
options.add_argument("enable-automation")
options.add_argument("--disable-infobars")
options.add_argument("--disable-dev-shm-usage")
options.add_argument("--remote-debugging-port=9230")
driver = webdriver.Chrome(options=options)
driver.get("https://google.com/")
print(driver.current_url)
print(driver.title)
driver.stop_client()
driver.close()
driver.quit()
